# Generated by Django 6.0.3 on 2026-03-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pov', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
