# Generated by Django 6.0.3 on 2026-04-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pov', '0005_alter_about_options_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
