# Generated by Django 6.0.3 on 2026-04-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pov', '0013_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
